// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAki7Ov0lcmHPpiKz05VKzo7Fs-8GjgmEg",
  authDomain: "saitronics-billing.firebaseapp.com",
  projectId: "saitronics-billing",
 storageBucket: 'saitronics-billing.appspot.com',

  messagingSenderId: "920202245192",
  appId: "1:920202245192:web:20b64c014321ab9eb9147d",
  measurementId: "G-2KR8CZLJ5S"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOd6DNI55VjWj2yCydwKOib0SsRxRhi64',
    appId: '1:920202245192:android:7e077699ab161c1ab9147d',
    messagingSenderId: '920202245192',
    projectId: 'saitronics-billing',
    storageBucket: 'saitronics-billing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8NLUfIrLCk0uUZex0SNf1vPTZuomFAuQ',
    appId: '1:920202245192:ios:db14b07737b6c580b9147d',
    messagingSenderId: '920202245192',
    projectId: 'saitronics-billing',
    storageBucket: 'saitronics-billing.firebasestorage.app',
    iosBundleId: 'com.example.saitronicsBilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8NLUfIrLCk0uUZex0SNf1vPTZuomFAuQ',
    appId: '1:920202245192:ios:db14b07737b6c580b9147d',
    messagingSenderId: '920202245192',
    projectId: 'saitronics-billing',
    storageBucket: 'saitronics-billing.firebasestorage.app',
    iosBundleId: 'com.example.saitronicsBilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAki7Ov0lcmHPpiKz05VKzo7Fs-8GjgmEg',
    appId: '1:920202245192:web:8a9b358100b977ddb9147d',
    messagingSenderId: '920202245192',
    projectId: 'saitronics-billing',
    authDomain: 'saitronics-billing.firebaseapp.com',
    storageBucket: 'saitronics-billing.firebasestorage.app',
    measurementId: 'G-NQKXGP76RX',
  );
}
